// <auto-generated />
using DapperLinqScaffold.Database.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DapperLinqScaffold.Database.Migrations
{
    [DbContext(typeof(DapperLinqScaffoldDbContext))]
    partial class DapperLinqScaffoldDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DapperLinqScaffold.Data.POCO.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HeroTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Legolas",
                            Power = 80,
                            RaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Elrond",
                            Power = 85,
                            RaceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Solid Snake",
                            Power = 75,
                            RaceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cloud",
                            Power = 70,
                            RaceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zack",
                            Power = 80,
                            RaceId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Obi-Wan Kenobi",
                            Power = 90,
                            RaceId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Anakin Skywalker",
                            Power = 95,
                            RaceId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gandalf",
                            Power = 95,
                            RaceId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Count Dooku",
                            Power = 100,
                            RaceId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "Darth Maul",
                            Power = 85,
                            RaceId = 5
                        });
                });

            modelBuilder.Entity("DapperLinqScaffold.Data.POCO.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RaceTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elf"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Human"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jedi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Maiar"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
